version: '3.5'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=sports_db
    image: postgres:15.5-alpine
    