name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Clone beerchan_bot repository and install dependencies
      run: |
        git clone https://github.com/beerchan-edu/beerchan-bot.git beerchan_bot
        cd beerchan_bot
        git checkout a8c796cf7a24a80b3897b1e4b6bfc055c47f9200
        pip install -r requirements.txt

    - name: Install package in editable mode
      run: |
        pip install -e .

    - name: Run tests
      run: |
        pytest tests
